services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nginx-web1
      - nginx-web2

  nginx-web1:
    image: nginx:latest
    volumes:
      - ./web1:/usr/share/nginx/html:ro
    expose:
      - "80"

  nginx-web2:
    image: nginx:latest
    volumes:
      - ./web2:/usr/share/nginx/html:ro
    ports:
      - "80"
    deploy:
      replicas: 3
